---
- name: MongoDB | Add MongoDB apt key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=7F0CEB10

- name: MongoDB | Create MongoDB Lists File
  shell: echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list

- name: MongoDB | Update apt
  apt: update_cache=yes

- name: MongoDB | Create MongoDB Data Directory
  file: path=/data/db state=directory mode=0755

- name: MongoDB | Install MongoDB 3
  apt: pkg=mongodb-org state=latest force=yes